### ISSUE TITLE
Support for Eloquent SoftDeletes trait

### ISSUE THREAD

**Issue by dinamic** [michaeljennings/laralastica#17]
Our use case includes updating entries that are already soft-deleted. In such an instance, when attributes change, they should not be communicated to Elasticsearch. The update should rather be ignored.

The goal is for soft-deleted entries to only be found in the database, not in Elasticsearch.

I guess I could hook in this logic myself, but I wonder what would the proper place be? Is there a sensible way to use a custom observer class, so I can override the `created()` method?

**Comment by dinamic** [comment]
I imagine the fix for this to be like:

```
    public function created(Model $model)
    {
        if ($model instanceof \Illuminate\Database\Eloquent\SoftDeletes::class && $model->trashed()) {
            return;
        }

        event(new IndexesWhenSaved($model));
    }
```

**Comment by michaeljennings** [comment]
Yeah that would work.

You could 'extend' the searchable trait and override the `bootSearchable` method to pass in your own custom observer.

```php
use Michaeljennings\Laralastica\Searchable;

trait CustomSearchable
{
    use Searchable;

    /**
     * Boot the trait.
     */
    protected static function bootSearchable()
    {
        if ( ! is_null(static::$dispatcher)) {
            static::observe(new CustomObserver(static::$dispatcher));
        }
    }
}
```

Then just use the new `CustomSearchable` trait as you would the default `Searchable` trait.

Alternatively if you're happy for soft-deleted results to be indexed you can use the `SearchSoftDeletes` trait. By default soft-deleted records will be ignored when searching, but it gives you the option to search soft-deleted records.

**Comment by dinamic** [comment]
That's the way I went. Thanks, @michaeljennings!
