### ISSUE TITLE
No listeners in Laravel 5.1

### ISSUE THREAD

**Issue by ceesvanegmond** [michaeljennings/laralastica#2]
I've had some issues with this package in combination with Laravel 5.1.
Because of some ServiceProvider changes.

Default, the ServiceProvider is ```$defer = true```. 
This means that all the listeners in the serviceprovider are not being loaded by default.

So for instance, if I want to add all say pages to elastic, i want to do something like this:

```php
<?php

Route::get('/', function() {
    foreach(Page::all() as $page) {
       $page->save();
    }
});
```

Because the service providers defer is true, the events that are being fired from above piece of code arend handled, because the listeners arent initialized.

When I set the defer to false, above piece of code is working.
What can we do about this?

**Comment by michaeljennings** [comment]
Sorry that's my fault I didn't think that part through in the update.

I'm not sure if adding the events (i.e. `Michaeljennings\Laralastica\Events\IndexesWhenSaved`) into the provides array would fix the issue?

If that doesn't work then I'll revert the change and make the stop the service provider being deferred in the next release.

For the minute to get it working I'd recommend creating a new service provider, that extends the default one, and then set `$defer = false` in there.

**Comment by ceesvanegmond** [comment]
Thank you for your reply.
I'm afrait the ```provides()``` function isn't used anymore in Laravel 5+.

The ```$defer``` has to be set to ```false```

**Comment by michaeljennings** [comment]
No problem, I've had a look and the provides method does still work in Laravel 5+, however it doesn't seem to work with the events so I'll merge your pull request now.

Cheers for the fix, if you find anything else feel free to raise an issue.

**Comment by ceesvanegmond** [comment]
Hmmm thats weird. It doesnt say anything about it in the docs. 

Could you tag the latest release please?

**Comment by michaeljennings** [comment]
It's under the providers section in the docs, [link here](http://laravel.com/docs/5.1/providers#deferred-providers).

Yeah sure I'll add v1.2.4 now.

**Comment by ceesvanegmond** [comment]
Alright, thx. If you have a better solution, please make it better.
